[project]
name = "groq-llamaindex-py"
version = "0.1.0"
description = "Groq llama-index python examples"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "llama-index-llms-groq>=0.3.2",
]
